# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{crumble}
  s.version = "0.1.2"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Mathias Meyer"]
  s.date = %q{2010-08-25}
  s.description = %q{How did these breadcrumbs in your Rails application? Oh right, with this plugin!}
  s.email = %q{meyer@paperplanes.de}
  s.extra_rdoc_files = [
    "README.md"
  ]
  s.files = [
    ".gitignore",
     "README.md",
     "Rakefile",
     "VERSION",
     "app/helpers/breadcrumbs_helper.rb",
     "lib/breadcrumb.rb",
     "lib/crumble/railtie.rb",
     "rails/init.rb",
     "spec/breadcrumb_spec.rb",
     "spec/breadcrumbs_helper_spec.rb",
     "spec/spec_helper.rb",
     "examples/another_breadcrumbs_helper.rb"
  ]
  s.homepage = %q{http://github.com/kryzhovnik/crumble}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{Crumble - It's like breadcrumbs for your Rails application!}
  s.test_files = [
    "spec/breadcrumbs_helper_spec.rb",
     "spec/breadcrumb_spec.rb",
     "spec/spec_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

